apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mp-booking-dp
  labels:
    app: mp-booking
    chart: "mp-booking-{{ .Values.global.tag }}" 
    release: {{ .Values.global.tag }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: mp-booking-rc    
      labels:
        app: mp-booking
        release: {{ .Values.global.tag }}
    spec:
      containers:
        - name: mp-booking
          image: "{{ .Values.image.repository }}:{{ .Values.global.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NACOS_HOST
            value: "nacos-headless"
          - name: NACOS_NAMESPACE
            value: "09c4e3f4-3650-4df4-be01-8d994876fd58"
          - name: LOGSTASH_HOST
            value: "172.16.99.187"         
          - name: SPRING_PROFILES_ACTIVE
            value: "{{ .Values.global.deploymentenv }}"
          - name: JAVA_OPTS
            value: "-Xms512m -Xmx512m"           
          ports:
          - name: tcp
            containerPort: {{ .Values.ports.containerport }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
