kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mp4cloud-cephfs-sc
provisioner: ceph.com/cephfs
parameters:
    monitors: 172.16.20.11:6789,172.16.20.12:6789,172.16.20.13:6789
    adminId: admin
    adminSecretName: ceph-admin-secret
    adminSecretNamespace: kube-system 
