---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mp4cloud-ceph-rbd-sc 
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-slave-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mp4cloud-ceph-rbd-sc 
  resources:
    requests:
      storage: 5Gi
