replicaCount: 1

deploymentenv: dev

image:
  repository: harbor.frcloud.io/test/agency
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  host: agency.frcloud.io
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
