{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mp-edo.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mp-edo-ingress
  labels:
    app: mp-edo
    chart: "mp-edo-{{ .Values.global.tag }}" 
    release: {{ .Values.global.tag }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      - {{.Values.ingress.host}}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: {{ .Values.ports.serviceport }} 
{{- end }}
