apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mp-auth-tringress 
spec:
  rules:
  - host: auth.mp4cloud.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: mp-auth-svc 
          servicePort: 3000 
