apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mp-monitor-ingress
  namespace: mp4cloud
  annotations:
    nginx.ingress.kubernetes.io/rewite-target: /
spec:
  rules:
  - host: monitor.mp4cloud.com
    http:
      paths:
      - path:
        backend:
          serviceName: mp-monitor-svc
          servicePort: 5001 
