apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mp-webapp-ingress
  namespace: mp4cloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.mp4cloud.com
    http:
      paths:
      - path:
        backend:
          serviceName: mp-webapp-svc
          servicePort: 8080
