apiVersion: v1
kind: Service
metadata:
  name: mp-monitor-svc
  labels:
    app: mp-monitor
    chart: "mp-monitor-{{ .Values.global.tag }}" 
    release: {{ .Values.global.tag }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.serviceport }}
      nodePort: {{ .Values.ports.nodeport }}
      targetPort: {{ .Values.ports.containerport}}
      name: api
  selector:
    app: mp-monitor
    release: {{ .Values.global.tag }}
