apiVersion: v1
kind: Service
metadata:
  name: mp-auth-svc
  labels:
    app: mp-auth
    chart: "mp-auth-{{ .Values.global.tag }}" 
    release: {{ .Values.global.tag }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mp-auth
    release: {{ .Values.global.tag }}
